# Generated by Django 4.0.4 on 2022-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
